### ISSUE TITLE
When using pip install an older version of the code is being installed

### ISSUE THREAD

**Issue by John-Male** [oz123/pytest-localftpserver#13]
I installed using the plugin using pip. I encountered a few different problems when I tried to use the plugin. In debugging the problem I encountered I ended up looking at the code that was present from the pip install. 

I found that I had an older version of the plugin.py file than the one present in the repo. I replaced the code in the plugin.py with the code that is present in the repo and then the problem was resolved. 

Before I made this change I did run a check for the version of the plugin that was installed by pip. The error I was receiving was 

WinError 10038] An operation was attempted on something that is not a socket

I was executing the code on a Windows 7 OS

**Comment by s-weigand** [comment]
This is related to #10 , since the old version on PyPi doesn't work on Windows and Osx Systems (versions on PyPi are only a snapeshot from from the code at the momement of the release).

Until the new version is on pip, the workaround would be `pip install git+https://github.com/oz123/pytest-localftpserver.git`.
After the new version is released, you can make sure that the minimum requirenets are fulfilled by using `pip install "pytest-localftpserver>0.4.1"`

PS.: If you develope a package just drop the `pip install` to be able to wirite the dependency in your `setup.py` or `requirements.txt`

**Comment by oz123** [comment]
I released a new version to pypi. @s-weigand  thanks for your work!
