### ISSUE TITLE
Operation not supported

### ISSUE THREAD

**Issue by Zujiry** [oz123/pytest-localftpserver#98]
So what I want to do, is to create a folder on the ftp server via ftplib.

What I do is:
```
ftp = FTP()
ftp.connect('127.0.0.1', cfg['test_server']['port'])
ftp.login(cfg['test_server']['user'], cfg['test_server']['password'])
ftp.mkd('/home/test_files')
```

What I get is:
ftplib.error_perm: 550 No such file or directory.
In other cases I get 550: Operation not supported.

I have no clue what the problem is with my permissions. I configured user and password in the pytest.ini and checked via ftpserver.username which works. Could it be, that I need permissions somewhere in my own filesystem?

+ If I set my homefolder to /home/test_files, the folder does not exist. Should that not be created?

**Comment by s-weigand** [comment]
My guess is `mkd` tries to create a folder at the absolute path `/home/test_files`, and if your FTP home folder isn't `/`, this is outside of the ftp home folder and thus not allowed. Try to use relative paths not absolute ones. 
Creating folders does work for sure and is tested.
https://github.com/oz123/pytest-localftpserver/blob/2d8cc2a1e2c1e76075b8028864a4c8304f27777f/tests/test_pytest_localftpserver.py#L331-L349

Also I don't know if `mkd` supports creating folder structures or if you have to create them one by one.
i. e.:
```python
ftp.mkd('parent_folder')
ftp.cwd('parent_folder')
ftp.mkd('child_folder')
```

**Comment by Zujiry** [comment]
Thanks for your answer.

Okay, so the problem was, that I did not have permission to write into my root directory, as the ftp server starts from root. I thought it would start in a tmpdir (reading helps...).

What I did is to write into pytest.ini: FTP_HOME=path/of/tmpdir to solve this problem which helps with the 550. But I can not find a way to write into the pytest.ini before the ftp_server starts, so I have to always restart at least once. 
autouse=True or / and scope=module should start another fixture before the ftp_server? Did I missunderstand something?

**Comment by s-weigand** [comment]
The default behaviour is that `FTP_HOME` and `FTP_HOME_TLS`, are tmp dirs (since the anon user has only read permissions it is allways a temp folder).
When you set those values in your `pytest.ini` you overwrite the default behaviour. This thought for cases where you want to test in combination with an external service (i.e. WebServer), where you need to provide the path beforehand.
https://github.com/oz123/pytest-localftpserver/blob/93a414a9139d6f618b61f962139a16cf7993c29d/pytest_localftpserver/servers.py#L61-L70

The fixtures `ftpserver` and `ftpserver_TLS` are both module scope fixtures, so the ftp servers get started at the beginning of a test file (module) and stoped when the file is done.

I don't understand the use case for changing `FTP_HOME` mid test, maybe you can elaborate on what you try to test with an example, so it is more clear what you want to achieve.

Judging from the code you posted before, I guess you didn't yet read the [part in the docs concerning the High-Level Interface](https://pytest-localftpserver.readthedocs.io/en/latest/usage.html#high-level-interface).
If you just want to populate and depopulate files and folders on the FTP to setup you testing state, this is the way to go.
For detailed information on all available methods have a look at the [API documentation](https://pytest-localftpserver.readthedocs.io/en/latest/api/pytest_localftpserver.servers.FunctionalityWrapper.html#).

**Comment by Zujiry** [comment]
Thank you very much, I did overread the default behavior somehow.
